package net.atos.wolf.services.action;

public enum ActionType {
    CHANGE_SECTION,
    CHANGE_SECTION_IF_SKILL,
    CHANGE_SECTION_IF_WEAPON,
    CHANGE_SECTION_IF_SPECIAL_ITEM,
    CHANGE_SECTION_IF_NO_OTHER_OPTION,
    TAKE_WEAPON,
    INITIALIZE_ATTRIBUTE,
    CHANGE_SECTION_IF_NUMBER_OF_SKILLS,
    GET_KAI_SKILL,
    GET_KAI_SKILL_AND_PICK_WEAPON,
    GET_INITIAL_ITEMS,
    TAKE_RANDOM_WEAPON,
    CHANGE_SECTION_IF_RANDOM,
    MODIFY_ATTRIBUTE


}
