package net.atos.wolf.services.action;

public enum ActionType {
    CHANGE_SECTION,
    CHANGE_SECTION_IF_SKILL,
    CHANGE_SECTION_IF_WEAPON,
    CHANGE_SECTION_IF_SPECIAL_ITEM,
    CHANGE_SECTION_IF_NO_OTHER_OPTION,
    TAKE_WEAPON,
    INITIALIZE_ATTRIBUTE
}
